
![image](../Utilities/datacleaning.png)

__Author: Christian Urcuqui__

__Date: 23 August 2018__



# Data Cleaning and Preparation


Data cleaning and preparation is the process that we would spend more time in our data science projects, and it depends of the information complexity and it's problems. In this notebook we will see the different methods in Python in order to transform our raw data in tidy data for the next analyses. 

This notebook is divided in:

+ [Introduction](#Introduction)
+ [Handling Missing Data](#Handling-Missing-Data)
+ [Filtering out missing data](#Filtering-out-missing-data)
+ [Filling In Missing Data](#Filling-In-Missing-Data)
+ [Verifying the Format and the Variable Types](#Verifying-the-Format-and-the-Variable-Types)
+ [Discretization and Binning](#Discretization-and-Binning)
+ [Detecting and Filtering Outliers](#Detecting-and-Filtering-Outliers)
+ [Preprocessing Data](#Preprocessing-Data)
+ [References](#References)


## Introduction

We can have different situations or problems in our datasets, in order to find them we must have pay attention to the data dictionary. 


## Handling Missing Data

Missing data appears in many data projects due different complex situations, such as human and system problems. Pandas associates these missing values with the floating-point value NaN (Not a Number).

In [35]:
from pandas import Series
import numpy as np

example = Series(['ftp', 'ssh', np.nan, 'icmp'])

example

0     ftp
1     ssh
2     NaN
3    icmp
dtype: object

In [4]:
example.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [5]:
example.isna

<bound method Series.isna of 0     ftp
1     ssh
2     NaN
3    icmp
dtype: object>

The value None in Python is also treated as NA in object arrays

In [7]:
example[0] = None

example.isnull()

0     True
1    False
2     True
3    False
dtype: bool

Some methods for NA handling are:
+ _dropna_, filter and erase each NA value associated to a axis label
+ _fillna_, fill in missing data with some value or by a method such as 'ffill' or 'bfill'
+ _isnull_, it returns a list of boolean values associated to the missing values.
+ _notnull_, negation of isnull


## Filtering out missing data

Using some of the methods previously metioned we can filter the NaNs in our datasets.

In [11]:
from numpy import nan as NA
import pandas as pd

data = Series([1, NA, 2.5, NA, 9])

data.dropna()

0    1.0
2    2.5
4    9.0
dtype: float64

In [13]:
data[data.notnull()]

0    1.0
2    2.5
4    9.0
dtype: float64

In the next examples we will se the same application of filtering in DataFrame objects. By default _dropna_ erases all the rows that have NaNs.

In [15]:
from pandas import DataFrame

data = DataFrame([[1., 6.5, 3.], [1., NA, NA], [NA, NA, NA], [NA, 6.5, 3.]])

cleaned = data.dropna()

data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [16]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [27]:
# pay attention to the parameter in the dropna method, if we specify how=all we are traying to erase only the rows that have all the values in NaNs
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

If we want to erase the columns that have the same way of NaNs in all of their values we can use axis=1

In [28]:
data[4] = None
data

0    1    2     4
0  1.0  6.5  3.0  None
1  1.0  NaN  NaN  None
2  NaN  NaN  NaN  None
3  NaN  6.5  3.0  None

In [29]:
data.dropna(axis=1, how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

If we only want to keep a certain number of observations, remember that we can select them with the method iloc from the object DataFrame

In [30]:
# we will make the dataframe to process
import numpy as np
df = DataFrame(np.random.rand(7,3))
df

0         1         2
0  0.822287  0.745434  0.374203
1  0.953188  0.727975  0.304002
2  0.283246  0.006190  0.047044
3  0.575857  0.720681  0.979117
4  0.513575  0.636307  0.847163
5  0.165529  0.937517  0.423376
6  0.188833  0.944823  0.072005

In [32]:
df.iloc[:4, 1] = NA # We are changing the first four rows in the second column to NaNs

df.iloc[:2, 2] = NA 

df


0         1         2
0  0.822287       NaN       NaN
1  0.953188       NaN       NaN
2  0.283246       NaN  0.047044
3  0.575857       NaN  0.979117
4  0.513575  0.636307  0.847163
5  0.165529  0.937517  0.423376
6  0.188833  0.944823  0.072005

The idea is to specify the parameter thresh that allows to define the rows that we will keep and the method will not erase it

In [34]:
df.dropna(thresh=2)

0         1         2
2  0.283246       NaN  0.047044
3  0.575857       NaN  0.979117
4  0.513575  0.636307  0.847163
5  0.165529  0.937517  0.423376
6  0.188833  0.944823  0.072005

## Filling In Missing Data




We can use different methods in order to fill the missing data, one of them is to use the _fillna_ method with a constant value, this method will replace the NaNs with the constant defined in the parameter.

In [36]:
df.fillna(0)

0         1         2
0  0.822287  0.000000  0.000000
1  0.953188  0.000000  0.000000
2  0.283246  0.000000  0.047044
3  0.575857  0.000000  0.979117
4  0.513575  0.636307  0.847163
5  0.165529  0.937517  0.423376
6  0.188833  0.944823  0.072005

In the same way we can use a dictionary in order to define more specifically the data to replace in the NaNs

In [38]:
df.fillna({1:0.5, 2:0}) # pay attention that this method searches and replaces by indexes of the columns 

0         1         2
0  0.822287  0.500000  0.000000
1  0.953188  0.500000  0.000000
2  0.283246  0.500000  0.047044
3  0.575857  0.500000  0.979117
4  0.513575  0.636307  0.847163
5  0.165529  0.937517  0.423376
6  0.188833  0.944823  0.072005

In the same way we can use methods incorporated in _fillna_, specifically, fill NaN values using interpolation.

https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.fillna.html
 ```
method : {‘backfill’, ‘bfill’, ‘pad’, ‘ffill’, None}, default None

Method to use for filling holes in reindexed Series pad / ffill: propagate last valid observation forward to next valid backfill / bfill: use NEXT valid observation to fill gap
 ```


In [39]:
df2 = DataFrame(np.random.randn(6,3))

df2.iloc[2:, 1] = NA
df2.iloc[4:, 2] = NA

df2

0         1         2
0 -1.529642 -1.908967  1.193810
1 -0.083051 -1.171295 -0.063588
2 -0.403066       NaN -0.732555
3  0.894471       NaN -1.013693
4  0.878349       NaN       NaN
5  0.508237       NaN       NaN

In [43]:
df2.fillna(method = 'ffill')

0         1         2
0 -1.529642 -1.908967  1.193810
1 -0.083051 -1.171295 -0.063588
2 -0.403066 -1.171295 -0.732555
3  0.894471 -1.171295 -1.013693
4  0.878349 -1.171295 -1.013693
5  0.508237 -1.171295 -1.013693

In [44]:
df2.fillna(method = 'ffill', limit=2)

0         1         2
0 -1.529642 -1.908967  1.193810
1 -0.083051 -1.171295 -0.063588
2 -0.403066 -1.171295 -0.732555
3  0.894471 -1.171295 -1.013693
4  0.878349       NaN -1.013693
5  0.508237       NaN -1.013693

But, sometimes is important to evaluate first other methods to fill our data, for example through the application of the basic statistics

In [46]:
data = Series ([1., NA, 3.5, NA, 7])

data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

## Verifying the Format and the Variable Types

As we saw in the introduction, one of the usual issues in a dataset is the format and the type of variables related with the data dictionary, we must be careful because sometimes when we load the dataset the method loads the data with some predefined type of variables, due this we need to review the data and solve this problem in order to continue in the project. 

In [23]:
# we will use the iris dataset to verify the type of the data 
import seaborn as sns
data_iris = sns.load_dataset('iris')

print(type(data_iris))
print(data_iris.shape)

<class 'pandas.core.frame.DataFrame'>
(150, 5)


In [24]:
data_iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [25]:
data_iris.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [35]:
data_iris.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

In [31]:
data_iris2 = data_iris
print(data_iris2.columns)
# we will change the type of the column target (float64) to a categorical variable
data_iris2.species = data_iris2.species.astype('category')
print(data_iris2.dtypes)
print(data_iris2.head())

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')
sepal_length     float64
sepal_width      float64
petal_length     float64
petal_width      float64
species         category
dtype: object
   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa


## Removing duplicates

Another problem is the duplicate data in the dataset, we must be careful with this problem because the descriptive and predictive analyses might be wrong if we have a lot of them

In [53]:
data = DataFrame({'k1': ['one', 'two'] * 3 + ['two'], 
                 'k2': [1,1,2,3,3,4,4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

The method _duplicated_ from pandas returns an array of boolean Series whose allows us to understand if we have rows repeated.

In [55]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

We can erase them with the method (__drop_duplicates__) from the DateFrame object. By default the method will erase the first duplicated row, but we can change it with the parameter _keep=last_.

In [56]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [57]:
data.drop_duplicates(keep='last')

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
6  two   4

## Discretization and Binning

Continuous data is often discretized or otherwise separated into "bins" for analysis. Suppose you have an array of ages and you want to discrete them in age buckets.

In [59]:
import pandas as pd

ages = [20 , 22, 27, 21, 23, 37, 32, 45, 15]

# we will divide them in the next age buckets, such as 18 to 25, 22 to 25.

btns = [18, 25, 35, 60, 100]

cats =  pd.cut(ages, btns)

cats

[(18, 25], (18, 25], (25, 35], (18, 25], (18, 25], (35, 60], (25, 35], (35, 60], NaN]
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

Pay attention that we have now a special Categorical object, we can access to their indexes and the number of values in each bucket.

In [61]:
# we will display the codes of each bucket
cats.codes

array([ 0,  0,  1,  0,  0,  2,  1,  2, -1], dtype=int8)

In [63]:
# we will display the categories associated to each bucket
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]]
              closed='right',
              dtype='interval[int64]')

In [64]:
# we will count the number of values in each bucket
pd.value_counts(cats)

(18, 25]     4
(35, 60]     2
(25, 35]     2
(60, 100]    0
dtype: int64

In order to provide more information to the previous structure we can make the bin names 

In [67]:
group_names = ['Youth', 'YouthAdult', 'MiddleAged', 'Senior']
pd.cut(ages, btns, labels=group_names)

[Youth, Youth, YouthAdult, Youth, Youth, MiddleAged, YouthAdult, MiddleAged, NaN]
Categories (4, object): [Youth < YouthAdult < MiddleAged < Senior]

## Detecting and Filtering Outliers

The next method allows us to understand how the data in a DataFrame is distributed.

In [2]:
import pandas as pd
import numpy as np

data = pd.DataFrame(np.random.randn(1000, 4))

data.describe() # Describe only will make the statistics for the numerical variables in our DataFrame

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.052264     0.029412     0.046613    -0.054591
std       1.008821     1.013841     1.017611     1.003932
min      -2.705407    -3.091792    -3.152901    -3.945271
25%      -0.655582    -0.637948    -0.650335    -0.737302
50%       0.035707     0.082358     0.039698    -0.047301
75%       0.729648     0.731296     0.689248     0.584521
max       4.061342     3.050059     3.337478     3.086532

In [6]:
from numpy import nan as NA

df2 = pd.DataFrame(np.random.randn(6,3))

df2.iloc[2:, 1] = NA
df2.iloc[4:, 2] = NA

df2.describe() # In the same way, we must be careful with the NaNs

0         1         2
count  6.000000  2.000000  4.000000
mean  -0.027527 -0.415458 -0.381949
std    1.042294  2.175007  0.954860
min   -1.412719 -1.953420 -1.432180
25%   -0.867146 -1.184439 -0.896038
50%    0.253997 -0.415458 -0.467776
75%    0.788488  0.353522  0.046314
max    1.013769  1.122503  0.839937

In [13]:
df_park = pd.read_csv('../datasets/parks.csv', index_col=['Park Code'], encoding='utf-8')
print(df_park.head())

df_park.describe() # Look that the describe method only gives us the information about the numerical variables 

                        Park Name State   Acres  Latitude  Longitude
Park Code                                                           
ACAD         Acadia National Park    ME   47390     44.35     -68.21
ARCH         Arches National Park    UT   76519     38.68    -109.57
BADL       Badlands National Park    SD  242756     43.75    -102.50
BIBE       Big Bend National Park    TX  801163     29.25    -103.25
BISC       Biscayne National Park    FL  172924     25.65     -80.08


Acres   Latitude   Longitude
count  5.600000e+01  56.000000   56.000000
mean   9.279291e+05  41.233929 -113.234821
std    1.709258e+06  10.908831   22.440287
min    5.550000e+03  19.380000 -159.280000
25%    6.901050e+04  35.527500 -121.570000
50%    2.387645e+05  38.550000 -110.985000
75%    8.173602e+05  46.880000 -103.400000
max    8.323148e+06  67.780000  -68.210000

In [14]:
# if we want to have the statistics for all the variables we need to add the parameter include = 'all'
df_park.describe(include = 'all')

Park Name State         Acres   Latitude  \
count                                      56    56  5.600000e+01  56.000000   
unique                                     56    27           NaN        NaN   
top     Lake Clark National Park and Preserve    AK           NaN        NaN   
freq                                        1     8           NaN        NaN   
mean                                      NaN   NaN  9.279291e+05  41.233929   
std                                       NaN   NaN  1.709258e+06  10.908831   
min                                       NaN   NaN  5.550000e+03  19.380000   
25%                                       NaN   NaN  6.901050e+04  35.527500   
50%                                       NaN   NaN  2.387645e+05  38.550000   
75%                                       NaN   NaN  8.173602e+05  46.880000   
max                                       NaN   NaN  8.323148e+06  67.780000   

         Longitude  
count    56.000000  
unique         NaN  
top            NaN  
freq           NaN  
mean   -113.234821  
std      22.440287  
min    -159.280000  
25%    -121.570000  
50%    -110.985000  
75%    -103.400000  
max     -68.210000

## Computing Dummy Variables

It is a transformation technique for statistical modeling or machine learning applications, it allows us to convert a categorical variable into a "dummy" or "indicator" matrix. 

In [17]:
df = pd.DataFrame ({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                    'data': range(6)})
df

key  data
0   b     0
1   b     1
2   a     2
3   c     3
4   a     4
5   b     5

In [18]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In some cases, you may want to add a prefix to the columns in the indicator DataFrame, which can be merged with the other data. 

In [19]:
dummies = pd.get_dummies(df['key'], prefix='key')
df_with_dummy = df[['data']].join(dummies)
df_with_dummy


data  key_a  key_b  key_c
0     0      0      1      0
1     1      0      1      0
2     2      1      0      0
3     3      0      0      1
4     4      1      0      0
5     5      0      1      0

## Preprocessing Data

_Scikit learn_ provides the functions and transformer classes to change raw feature vectors into a representation that is more suitable for the training of the machine learning algorithms. 

The next examples were took from the scikit learn documentation.

### Standarization

__Standarization__ of datasets is a common requeriment for many machine learning algorithms; they might behave badly if the individual features do not look like standard normally distributed adta: Gaussian with zero mean and unit variance.

In this case the function _scale_ allows us to perform this operation on a single array-like dataset

In [36]:
from sklearn import preprocessing
import numpy as np

X_train = np.array([[1., -1, 2.],
                    [2., 0., 0.],
                    [0., 1., -1.]    
])
X_scaled = preprocessing.scale(X_train)

X_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

Scaled data has zero mean and unit variance

In [37]:
X_scaled.mean(axis=0)

array([0., 0., 0.])

In [38]:
X_scaled.std(axis=0)

array([1., 1., 1.])

The preprocessing module provides the class __StandardScaler__ that implements the _Transformer_ API to compute the mean and standard deviation on a training set so as to be able to later reapply the same transformation on the testing set.

In [39]:
scaler = preprocessing.StandardScaler().fit(X_train)
scaler

StandardScaler(copy=True, with_mean=True, with_std=True)

In [41]:
scaler.mean_

array([1.        , 0.        , 0.33333333])

In [42]:
scaler.scale_

array([0.81649658, 0.81649658, 1.24721913])

In [43]:
scaler.transform(X_train)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

The next step is to apply this scaler on new data (for the example the testing set)

In [44]:
X_test = [[-1., 1., 0.]]
scaler.transform(X_test)

array([[-2.44948974,  1.22474487, -0.26726124]])

We might disable either centering or scaling by the parameters __(with_mean=False)__ and __(with_std=False)__ in the StandardScaler.

### Scaling features to a range

Another way is scaling features to lie between a given minimum and maximum value, often between zero and one, or the maximum absolute value of each feature is scaled to unit size. 

In [47]:
# example to scale the data matrix to the [0,1] range

X_train = np.array([[ 1., -1., 2.],
                  [2., 0., 0.],
                  [0., 1., -1.]])
min_max_scaler = preprocessing.MinMaxScaler()
X_train_minmax = min_max_scaler.fit_transform(X_train)
X_train_minmax

array([[0.5       , 0.        , 1.        ],
       [1.        , 0.5       , 0.33333333],
       [0.        , 1.        , 0.        ]])

In the same way to the previous example the idea is to apply the scaler to some new test data unseen during the fit call. 

In [48]:
X_test = np.array([[-3., -1., 4.]])

X_test_minmax = min_max_scaler.transform(X_test)
X_test_minmax

array([[-1.5       ,  0.        ,  1.66666667]])

__MaxAbsScaler__ scales in a way that the traning data lies within the range [-1, 1] by the dividing through the largest maximum value in each feature.

In [49]:
X_train = np.array([[ 1., -1., 2.],
                  [2., 0., 0.],
                  [0., 1., -1.]])
max_abs_scaler = preprocessing.MaxAbsScaler()
X_train_maxabs = max_abs_scaler.fit_transform(X_train)
X_train_maxabs


array([[ 0.5, -1. ,  1. ],
       [ 1. ,  0. ,  0. ],
       [ 0. ,  1. , -0.5]])

In [50]:
X_test = np.array([[-3., -1., 4.]])

X_test_maxabs = max_abs_scaler.transform(X_test)
X_test_maxabs

array([[-1.5, -1. ,  2. ]])

### Normalization

__Normalization__ is the process of scaling individual samples to have unit norm. This process is useful to use a quadratic form such as the dot-product or any other kernel to quantify the similarity of any pair of samples.

The function _normalize_ allows us to perform this operation on a single array-like dataset, either using the l1 or l2 norms

In [52]:
X = [[1., -1., 2.],
    [2., 0., 0.],
    [0., 1., -1.]]
X_normalized = preprocessing.normalize(X, norm='l2')
X_normalized

array([[ 0.40824829, -0.40824829,  0.81649658],
       [ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.70710678, -0.70710678]])

Remember the idea is to make a normalizer in order to use in other data that we didn't use during the fit.

In [53]:
X = [[1., -1., 2.],
    [2., 0., 0.],
    [0., 1., -1.]]

normalizer = preprocessing.Normalizer().fit(X)
normalizer

Normalizer(copy=True, norm='l2')

In [54]:
normalizer.transform(X)

array([[ 0.40824829, -0.40824829,  0.81649658],
       [ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.70710678, -0.70710678]])

In [55]:
normalizer.transform([[-1.,  1., 0.]])  

array([[-0.70710678,  0.70710678,  0.        ]])

## References

+ http://scikit-learn.org/stable/modules/preprocessing.html#scaling-features-to-a-range